create or replace PROCEDURE ADDSALE 
(
  pProductID SALES.PRODUCT_ID%type,
  pSaleDate SALES.SALE_DATE%type,
  pQtySold SALES.QTYSOLD%type
)
AS
  CHECK_CONSTRAINT_VIOLATED EXCEPTION;
  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
BEGIN
  INSERT INTO SALES(SALEID, PRODUCT_ID, SALE_DATE, QTYSOLD)
    VALUES(SALES_ID_SEQ.nextval, pProductID, pSaleDate, pQtySold);
  
  UPDATE PRODUCT
  SET PRODUCT_STOCK = PRODUCT_STOCK  - pQtySold
  WHERE PRODUCT_ID = pProductID;
  
EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Product Stock cannot go below 0');
END;